name: "Bump"
description: "Determine the next semver release from the current release"
inputs:
  from:
    description: "Either an optionally prefixed `label` such as `major`, `minor`, `patch` or `prerelease` or a version number such as v0.0.0 or 0.0.0"
    required: true
  label-prefix:
    description: "Label prefix"
  release-prefix:
    description: "Release prefix"
    default: 'v'
  preid:
    description: "Pre-release id. If this is specified the release is considered a pre-release"
outputs:
  next-version:
    description: "Next semver release version (format: `major.minor.patch[-preid.N]`)"
  next-tag:
    description: "Next semver release tag (includes preid)"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - "--from"
    - "${{ inputs.from }}"
    - "--label-prefix"
    - "${{ inputs.label-prefix }}"
    - "--release-prefix"
    - "${{ inputs.release-prefix }}"
    - "--preid"
    - "${{ inputs.preid }}"
